I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2780, in script
    call screen happy_supervisor
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: Screen happy_supervisor is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2780, in script
    call screen happy_supervisor
  File "C:\Users\Gonzalo\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "C:\Users\Gonzalo\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Gonzalo\Desktop\renpy-8.0.3-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\Gonzalo\Desktop\renpy-8.0.3-sdk\renpy\exports.py", line 3167, in call_screen
    show_screen(_screen_name, _transient=True, *args, **kwargs)
  File "C:\Users\Gonzalo\Desktop\renpy-8.0.3-sdk\renpy\display\screen.py", line 1185, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen happy_supervisor is not known.


Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
A Day in the life of an intern 7.0
Tue Dec 13 20:35:03 2022
